/* ═══════════════════════════════════════════════════════════════════════
   Course content
   ───────────────────────────────────────────────────────────────────────
   Pure data, no DOM. course.js renders it and academy.js reads the
   module/unit counts for progress. Edit here to change the course.

   A unit is one of:
     kind: 'video'  — a YouTube lesson, optionally with a check quiz
     kind: 'quiz'   — a standalone assessment (module final, course exam)

   `correct` is the zero-based index into `a`.
   ═══════════════════════════════════════════════════════════════════════ */

window.COURSE = {
  id: 'sustainability-101',
  title: 'Introduction to Sustainability, Environment & Climate',
  tagline: 'The first-ever comprehensive video training platform on sustainability authored entirely in Armenian.',
  blurb: 'Funded by the European Union and designed for universal accessibility, with sign language translation and dual-language subtitles. Four modules take you from systems thinking to climate science, everyday green practice and, finally, to leading change yourself.',
  cover: 'Media/web/resources/course-cover.jpg',
  coverAlt: 'Course cover: the Armenian title \u201cԿայունություն, շրջակա միջավայր, կլիմա և ավելին\u201d over a bed of green moss, with Narek Ohanyan named as trainer',
  level: 'Beginner (introductory)',
  format: '15-part video training series, approx. 3 hours',
  access: 'Sign language, Armenian & English subtitles',
  author: 'Narek Ohanyan',
  price: 'Free',
  funder: 'European Union',
  passMark: 80,

  intro: { id: 'intro', kind: 'video', title: 'Welcome to the course', yt: 'xFEebOr8C4A' },

  modules: [
  /* ── Module 1 ───────────────────────────────────────────────────── */
  {
    id: 'm1', n: 1,
    title: 'Systems Thinking & Foundations of Sustainability',
    summary: 'How everything connects — and why a single change ripples outward.',
    units: [
      { id: 'm1-i', kind: 'video', title: 'Introduction', yt: 'b9Y3-hYwwrM' },
      { id: 'm1-1', kind: 'video', title: '1.1 Systems Thinking: Everything is Connected', yt: 'zvvg_W9eQxc',
        quiz: { title: 'Check what you learned', q: [
          { q: 'What is the primary focus of systems thinking in environmental science?',
            a: ['Analyzing nature, society, and the economy as completely isolated entities',
                'Understanding that all components form an interconnected web where one change impacts other parts',
                'Prioritizing short-term economic growth over ecological stability',
                'Studying biological organisms without considering human activity'],
            correct: 1,
            why: 'Systems thinking teaches us to see the whole picture and recognize that a single change (such as deforestation) causes domino effects across ecosystems, societies, and economies.' },
          { q: 'Which of the following represents a positive climate feedback loop described in the video?',
            a: ['Increased predator numbers reducing prey populations, leading to a natural balance',
                'Planting trees to absorb carbon dioxide and cool global temperatures',
                'Melting glaciers exposing darker surfaces that absorb more heat and accelerate further melting',
                'Soil erosion reducing river clarity and fish populations'],
            correct: 2,
            why: 'A positive feedback loop amplifies a process; melting ice reduces planetary reflectivity (albedo), causing exposed land or water to absorb more heat, which speeds up further melting.' }
        ]}},
      { id: 'm1-2', kind: 'video', title: '1.2 The Three Pillars of Sustainability', yt: 'Jg6MsQLJ8Fs',
        quiz: { title: 'Check what you learned', q: [
          { q: 'What are the three core pillars of sustainable development?',
            a: ['Technology, Agriculture, and Governance', 'Environment, Economy, and Society',
                'Climate, Energy, and Infrastructure', 'Education, Industry, and Globalization'],
            correct: 1,
            why: 'Sustainable development rests on three equal pillars: environmental protection, economic viability, and social equity.' },
          { q: 'Which initiative demonstrates an outcome at the intersection of all three pillars?',
            a: ['Building a coal-fired power plant to increase factory jobs',
                'Establishing green public transit that cuts air pollution, creates jobs, and improves public health',
                'Restricting human presence in a forest without providing local livelihood alternatives',
                'Increasing industrial manufacturing without waste disposal regulations'],
            correct: 1,
            why: 'Green public transport reduces air pollution (environment), creates employment (economy), and enhances community health and mobility (society).' }
        ]}},
      { id: 'm1-3', kind: 'video', title: '1.3 Environmental Justice & Accessibility', yt: 'WB4SIP_abtE',
        quiz: { title: 'Check what you learned', q: [
          { q: 'What is the core principle of environmental justice?',
            a: ['Ensuring every person has an equal right to clean air, water, and a safe environment regardless of background',
                'Equal distribution of industrial landfill sites across all geographical regions',
                'Giving wealthier nations priority access to global natural resources',
                'Allowing private companies to determine environmental safety rules'],
            correct: 0,
            why: 'Environmental justice asserts that clean air, clean water, and safe living environments are fundamental rights for everyone, regardless of socioeconomic status or location.' },
          { q: 'Why is accessibility (such as sign language interpretation or subtitles) critical in environmental safety?',
            a: ['It lowers the cost of broadcasting emergency programs',
                'It ensures vulnerable groups, such as deaf individuals, receive critical hazard warnings',
                'It eliminates the need for physical evacuation plans',
                'It satisfies administrative requirements without changing local outcomes'],
            correct: 1,
            why: 'Information accessibility ensures that emergency alerts and environmental education reach all community members without leaving anyone behind.' }
        ]}},
      { id: 'm1-4', kind: 'video', title: '1.4 The SDGs and Global Agenda 2030', yt: 'tMWneRuKeoE',
        quiz: { title: 'Check your knowledge', q: [
          { q: 'How does the United Nations define sustainable development?',
            a: ['Development that maximizes immediate financial profit from available natural resources',
                'Development that meets present needs without compromising the ability of future generations to meet their own needs',
                'Development focused strictly on expanding urban electrical grids by 2030',
                'Development that halts all industrial production in developing nations'],
            correct: 1,
            why: 'The UN definition emphasizes intergenerational equity — using resources responsibly today so future generations can thrive tomorrow.' },
          { q: 'How do the UN Sustainable Development Goals reflect systems thinking?',
            a: ['Each goal operates independently without affecting any other goal',
                'Progress on one goal (e.g. SDG 15: Life on Land) directly supports others (e.g. SDG 13: Climate Action and SDG 11: Sustainable Cities)',
                'The goals apply strictly to international organizations rather than local communities',
                'Achieving economic goals automatically fulfills environmental goals'],
            correct: 1,
            why: 'The 17 SDGs are deeply interconnected; taking action on land ecosystems helps regulate climate and improves urban air quality.' }
        ]}},
      { id: 'm1-s', kind: 'video', title: 'Module summary', yt: 'ps3Ci-llvPo' },
      { id: 'm1-f', kind: 'quiz', title: 'Module 1 final quiz', q: [
        { q: 'What is the core idea behind "systems thinking"?',
          a: ['Treating nature, society, and the economy as entirely separate topics',
              'Understanding that everything is connected in a large web and a single change affects many other parts',
              'Focusing only on the immediate cause of a problem without looking at long-term effects',
              'Believing that human activities have no impact on natural ecosystems'], correct: 1 },
        { q: 'What happens when the three pillars of sustainability are out of balance?',
          a: ['The economy grows faster', 'Society becomes more resilient',
              'The entire structure collapses, just like a building losing a foundation pillar',
              'Environmental resources are saved for the future'], correct: 2 },
        { q: 'Melting glaciers exposing darker land that absorbs more heat and causes more melting is an example of:',
          a: ['A negative feedback loop', 'A positive feedback loop', 'Sustainable development', 'Environmental justice'], correct: 1 },
        { q: 'What is the main principle of environmental justice?',
          a: ['Large, developed countries should have priority access to natural resources',
              'Only wealthy neighbourhoods need clean air and water',
              'Everyone, regardless of location, social status, or abilities, has an equal right to a clean and safe environment',
              'Environmental laws should only apply to factories, not individuals'], correct: 2 },
        { q: 'Why is translating extreme weather warnings into sign language important?',
          a: ['It makes the broadcast look more professional', 'It fulfills a financial requirement for the government',
              'It ensures information accessibility so vulnerable groups are not left behind during emergencies',
              'It helps reduce carbon emissions directly'], correct: 2 },
        { q: 'How does the United Nations define "sustainable development"?',
          a: ['Development that meets the needs of the present without compromising the ability of future generations to meet their own needs',
              'Halting all economic growth to protect natural resources completely',
              'Using up all current resources to build better technology for the future',
              'Prioritizing economic wealth over environmental and social health'], correct: 0 },
        { q: 'Which SDG focuses on reducing waste, recycling materials, and ensuring goods are used long-term?',
          a: ['SDG 6: Clean Water and Sanitation', 'SDG 7: Affordable and Clean Energy',
              'SDG 11: Sustainable Cities and Communities', 'SDG 12: Responsible Consumption and Production'], correct: 3 },
        { q: 'How does a green, electric public transport network reflect the three pillars?',
          a: ['It only helps the environment by reducing air pollution', 'It only helps the economy by creating jobs',
              'It cuts pollution (environment), creates new jobs (economy), and improves public health (society)',
              'It only helps society by giving people a way to travel'], correct: 2 },
        { q: 'How do the SDGs demonstrate systems thinking on a global scale?',
          a: ['Working on one goal, like protecting forests (SDG 15), also helps fight climate change (SDG 13) and keeps city air clean (SDG 11)',
              'Each of the 17 goals must be completed one at a time, in order',
              'Economic goals are entirely separate from environmental goals',
              'The goals only apply to rural areas, not cities'], correct: 0 },
        { q: 'According to the Global Agenda 2030, whose responsibility is it to achieve the SDGs?',
          a: ['Only the United Nations', 'Only national governments and politicians', 'Only large international businesses',
              'Everyone — including governments, businesses, scientists, communities, and individuals'], correct: 3 }
      ]}
    ]
  },

  /* ── Module 2 ───────────────────────────────────────────────────── */
  {
    id: 'm2', n: 2,
    title: 'Climate Science & Global Realities',
    summary: 'How the planet regulates itself, what we changed, and what it means for Armenia.',
    units: [
      { id: 'm2-i', kind: 'video', title: 'Introduction', yt: 'bvHLzm1YKKU' },
      { id: 'm2-1', kind: 'video', title: "2.1 Earth's Climate System", yt: 'mVmfdCvrYzw',
        quiz: { title: 'Check what you learned', q: [
          { q: 'What analogy does the video use to explain the difference between climate and weather?',
            a: ['Climate is like your daily outfit, while weather is your entire wardrobe',
                "Climate is like a person's long-term personality, while weather is their short-term mood",
                'Climate is like the ocean, while weather is like a river',
                'There is no difference; they mean the same thing'], correct: 1,
            why: 'Climate is the long-term average; weather is what is happening today.' },
          { q: "What would Earth's average temperature be without the natural greenhouse effect?",
            a: ['+15°C', '0°C', '−18°C', '+30°C'], correct: 2,
            why: 'Without the natural greenhouse effect the planet would average about −18°C — far too cold for life as we know it.' },
          { q: 'How do natural orbital changes (Milankovitch cycles) show that current warming is human-caused?',
            a: ['The natural cycles show the Earth should currently be in a cooling phase, yet the planet is rapidly warming',
                'The natural cycles show the sun is currently much hotter than usual',
                'Orbital changes prove that warming is completely natural',
                'The cycles show that volcanoes are currently releasing more CO2 than ever'], correct: 0,
            why: 'On orbital timescales we should be slowly cooling. The observed rapid warming runs against that trend.' }
        ]}},
      { id: 'm2-2', kind: 'video', title: '2.2 Human Impact', yt: 'Kn0becpyA6Q',
        quiz: { title: 'Check what you learned', q: [
          { q: 'How has atmospheric CO2 changed since the Industrial Revolution?',
            a: ['It decreased from 420 ppm to 280 ppm', 'It has remained stable at 280 ppm',
                'It increased from about 280 ppm to over 420 ppm', 'It increased from 100 ppm to 200 ppm'], correct: 2,
            why: 'Pre-industrial CO2 sat near 280 ppm; it now exceeds 420 ppm.' },
          { q: 'Why is deforestation a major contributor to climate change?',
            a: ["It increases the Earth's natural albedo", 'Without trees, natural cooling winds are blocked',
                'It removes a natural system that absorbs CO2, and burning or rotting trees release their stored carbon back into the atmosphere',
                "It causes the Earth's orbit to shift"], correct: 2,
            why: 'Deforestation is a double blow: it removes a carbon sink and releases the carbon already stored.' },
          { q: 'What does the video say about the global inequality of climate change?',
            a: ['Developing nations emit the most, while developed nations suffer the most',
                'Developed nations historically emitted the most, while developing nations and poor communities suffer the most severe impacts',
                'All countries emit equal amounts and suffer equally', 'Climate change only affects wealthy countries'], correct: 1,
            why: 'Responsibility and harm are unevenly distributed — the heart of climate justice.' }
        ]}},
      { id: 'm2-3', kind: 'video', title: '2.3 Regional Impact: Armenia and the Caucasus', yt: '0m6_rF6aZjg',
        quiz: { title: 'Check what you learned', q: [
          { q: "How has Armenia's climate changed over the past 90 years?",
            a: ['Temperature decreased by 1.3°C and precipitation increased by 9%',
                'Temperature increased by 1.3°C and precipitation decreased by about 9%',
                'Both temperature and precipitation have remained exactly the same',
                'Temperature increased by 5°C and precipitation dropped by 50%'], correct: 1,
            why: 'Armenia has warmed by about 1.3°C while precipitation has fallen roughly 9%.' },
          { q: 'What climate-related crisis is threatening Lake Sevan?',
            a: ['The lake is completely freezing over in the summer',
                'Increased temperatures and water level fluctuations are causing eutrophication and frequent algal blooms',
                'The water is becoming too salty for freshwater fish', 'The lake is turning into a glacier'], correct: 1,
            why: 'Warming and level change drive eutrophication, and algal blooms have become frequent.' }
        ]}},
      { id: 'm2-4', kind: 'video', title: '2.4 Mitigation & Adaptation', yt: 'JUyzOdvNL-Y',
        quiz: { title: 'Check what you learned', q: [
          { q: 'What does "mitigation" mean in climate action?',
            a: ['Adjusting to the impacts of climate change, like building flood walls',
                'Actions aimed at reducing the root causes of climate change, mainly by cutting greenhouse gas emissions',
                'Relocating populations to different countries', 'Ignoring the problem until new technology is invented'], correct: 1,
            why: 'Mitigation attacks the cause; adaptation manages the consequence.' },
          { q: 'Which of the following is an example of adaptation in Armenia?',
            a: ['Installing solar panels to generate clean energy', 'Switching to electric vehicles to reduce urban air pollution',
                'Implementing water-saving irrigation in the Ararat Valley and planting drought-resistant crops',
                'Restoring forests to absorb more CO2'], correct: 2,
            why: 'Water-saving irrigation and drought-resistant crops adjust to impacts already arriving.' }
        ]}},
      { id: 'm2-s', kind: 'video', title: 'Module summary', yt: 'PKHnqcTbzZg' },
      { id: 'm2-f', kind: 'quiz', title: 'Module 2 final quiz', q: [
        { q: "Which components make up the Earth's climate system?",
          a: ['Only the atmosphere and the sun', 'The atmosphere, oceans and water systems, land surface, ice and glaciers, and living organisms',
              'Only human industrial activities', 'The atmosphere and outer space'], correct: 1 },
        { q: 'What is the "albedo" effect?',
          a: ['The process of trees absorbing CO2 from the air', 'The reflection of solar energy away from Earth by clouds and ice',
              'The trapping of heat by greenhouse gases', 'The release of aerosols from factories'], correct: 1 },
        { q: 'Which best describes the greenhouse effect?',
          a: ['A completely unnatural process created by factories',
              'A natural process where gases like CO2 and methane trap heat to keep Earth warm, currently being dangerously amplified by human activity',
              'The process of the ozone layer blocking UV light', 'The cooling of the Earth due to volcanic eruptions'], correct: 1 },
        { q: 'Why is current warming not attributed to natural Milankovitch cycles?',
          a: ['Because natural cycles take millions of years to show any effect', 'Because the sun has stopped shining as brightly',
              'Because according to natural cycles the Earth should be entering a cooling phase, yet it is rapidly warming',
              'Because Milankovitch cycles only affect the oceans'], correct: 2 },
        { q: 'How much has atmospheric CO2 increased since the Industrial Revolution?',
          a: ['From 280 ppm to over 420 ppm', 'From 150 ppm to 280 ppm', 'It has doubled from 400 ppm to 800 ppm',
              'It has not increased; it has only changed locations'], correct: 0 },
        { q: 'What short-term climate effect do volcanic eruptions typically have?',
          a: ['They cause permanent global warming',
              'They cause temporary global cooling by releasing sulfur aerosols that reflect sunlight',
              'They completely destroy the greenhouse effect', 'They have no impact on the climate whatsoever'], correct: 1 },
        { q: "What is happening to groundwater in Armenia's Ararat Valley?",
          a: ['It is flooding due to excessive rainfall',
              'The water level is dropping rapidly due to decreased precipitation combined with water overuse',
              'It is becoming completely frozen due to harsh winters', 'It is remaining stable thanks to new conservation laws'], correct: 1 },
        { q: "How does climate change affect Armenia's mountains and hydropower?",
          a: ['Increased snowstorms are breaking power lines',
              'Glaciers are shrinking and the snow season is shorter, limiting spring runoff for reservoirs and irrigation',
              'The mountains are growing taller and blocking the wind', 'Too much water is causing dams to constantly overflow'], correct: 1 },
        { q: 'Which action is an example of climate mitigation?',
          a: ['Building a protective wall to stop river flooding', 'Developing early warning systems for extreme weather',
              'Transitioning from coal power to wind and solar energy', 'Creating emergency evacuation plans for farmers'], correct: 2 },
        { q: 'Why must mitigation and adaptation be used together?',
          a: ['Because one is for developed countries and the other for developing countries',
              'Because mitigation alone costs too much money',
              'Because we must adapt to impacts already happening, while mitigating to stop the root causes from making the crisis worse',
              'Because adaptation naturally stops greenhouse gas emissions on its own'], correct: 2 }
      ]}
    ]
  },

  /* ── Module 3 ───────────────────────────────────────────────────── */
  {
    id: 'm3', n: 3,
    title: 'Green Practices & Lifestyles',
    summary: 'What a circular economy, a food system and a household actually look like in practice.',
    units: [
      { id: 'm3-i', kind: 'video', title: 'Introduction', yt: 'jbzGtWHU-eE' },
      { id: 'm3-1', kind: 'video', title: '3.1 Circular Economy and Zero Waste', yt: 'XIRZg2_JHWw',
        quiz: { title: 'Check what you learned', q: [
          { q: 'What is the main difference between a linear and a circular economy?',
            a: ['A linear economy recycles everything, while a circular economy throws everything away',
                'A linear economy follows a "take, make, dispose" model, while a circular economy keeps resources in use for as long as possible',
                'A circular economy only applies to agriculture', 'A linear economy produces zero waste'], correct: 1,
            why: 'Linear runs in a straight line to the landfill; circular keeps material in play.' },
          { q: 'What are the four core actions for individuals transitioning to a circular economy?',
            a: ['Buy, Use, Store, Discard', 'Extract, Produce, Consume, Throw away',
                'Reduce, Reuse, Recycle, Repair', 'Burn, Bury, Hide, Forget'], correct: 2,
            why: 'Reduce, reuse, recycle and repair — in that order of preference.' },
          { q: 'What is the true goal of the "zero waste" approach?',
            a: ['To completely stop buying any goods or services',
                'To design products so they leave no waste, and to prioritize repairing and reusing over single-use culture',
                'To throw waste into the ocean instead of landfills', 'To only recycle plastic and ignore other materials'], correct: 1,
            why: 'Zero waste is a design principle, not an instruction to stop consuming.' }
        ]}},
      { id: 'm3-2', kind: 'video', title: '3.2 Food Systems and Sustainable Agriculture', yt: '1x0BG9dyhWQ',
        quiz: { title: 'Check what you learned', q: [
          { q: 'Approximately how much of global greenhouse gas emissions are linked to food?',
            a: ['About one-tenth (10%)', 'About one-quarter (25%)', 'About one-third (33%)', 'About three-quarters (75%)'], correct: 2,
            why: 'Around a third of global emissions trace to food production, processing and transport.' },
          { q: 'Which is a key practice of sustainable agriculture?',
            a: ['Using maximum amounts of chemical fertilizers to grow crops faster',
                'Wasting large amounts of water through inefficient irrigation',
                'Conserving water through drip irrigation and reducing the use of toxic chemicals',
                'Destroying local biodiversity to plant a single type of crop'], correct: 2,
            why: 'Efficient water use and reduced chemical load are core to sustainable farming.' },
          { q: 'How can consumers directly support sustainable food systems?',
            a: ['By exclusively buying imported, out-of-season products',
                'By choosing local and seasonal foods, reducing food waste, and supporting farmers markets',
                'By buying food packaged only in single-use plastic', 'By throwing away leftover food instead of planning meals'], correct: 1,
            why: 'Local, seasonal and low-waste choices shorten the supply chain and cut emissions.' }
        ]}},
      { id: 'm3-3', kind: 'video', title: '3.3 Sustainable Energy and Mobility', yt: 'Ln7t9H9KbCk',
        quiz: { title: 'Check what you learned', q: [
          { q: 'What does "energy efficiency" mean in daily life?',
            a: ['Using fossil fuels to get work done as fast as possible', 'Leaving lights on all day to keep the house warm',
                'Doing the same amount of work using less energy, such as using LED bulbs and insulating buildings',
                'Only using electricity during the nighttime'], correct: 2,
            why: 'Efficiency is the same output for less input — the cheapest energy is the energy you never use.' },
          { q: 'Which countries are highlighted as leaders in cycling as a primary transport method?',
            a: ['The United States and Canada', 'Denmark and the Netherlands',
                'Australia and New Zealand', 'Brazil and Argentina'], correct: 1,
            why: 'Denmark and the Netherlands built infrastructure that makes cycling the default choice.' },
          { q: 'Which is an example of sustainable mobility?',
            a: ['Driving alone in a gas-powered SUV for short distances',
                'Expanding public transportation, building bike lanes, and promoting electric vehicles',
                'Building more coal power plants to charge cars', 'Banning all forms of transportation'], correct: 1,
            why: 'Sustainable mobility shifts trips to lower-carbon modes rather than eliminating travel.' }
        ]}},
      { id: 'm3-4', kind: 'video', title: '3.4 Green Homes and Everyday Choices', yt: 'OAYIhiAeIOc',
        quiz: { title: 'Check what you learned', q: [
          { q: 'How can individuals practically save water at home?',
            a: ['By taking shorter showers, using water-saving taps, and harvesting rainwater',
                'By leaving the tap running while washing dishes or brushing teeth',
                'By boiling all rainwater before throwing it away', 'By stopping the consumption of drinking water'], correct: 0,
            why: 'Small fixtures and habits compound into large household savings.' },
          { q: 'What does supporting "slow fashion" mean?',
            a: ['Buying clothes that take a long time to put on',
                'Buying high-quality, long-lasting clothing and exploring second-hand markets to reduce waste',
                'Buying cheap, trendy clothes every week and throwing them away',
                'Making clothes entirely out of single-use plastics'], correct: 1,
            why: 'Slow fashion favours durability and reuse over disposable trend cycles.' }
        ]}},
      { id: 'm3-s', kind: 'video', title: 'Module summary', yt: 'YaNe5WAZwAU' },
      { id: 'm3-f', kind: 'quiz', title: 'Module 3 final quiz', q: [
        { q: 'In a linear economy, what typically happens to a product at the end of its life?',
          a: ['It is repaired and sold again', 'It is broken down and fully recycled',
              'It is thrown away as waste in a landfill', 'It is composted to feed the soil'], correct: 2 },
        { q: 'Why is a short supply chain better for the environment?',
          a: ['It requires more plastic packaging',
              'It requires significantly less transportation and processing, which reduces greenhouse gas emissions',
              'It makes the food much more expensive', 'Short supply chains only sell unhealthy food'], correct: 1 },
        { q: 'What is the primary purpose of composting at home?',
          a: ['To create alternative fuels for cars',
              'To recycle food scraps and organic waste back into nutrient-rich soil, keeping it out of landfills',
              'To clean dirty tap water', 'To safely dispose of batteries and electronics'], correct: 1 },
        { q: 'Which energy source is considered sustainable and renewable?',
          a: ['Coal', 'Natural gas', 'Solar and wind', 'Oil'], correct: 2 },
        { q: 'Switching to LED bulbs, unplugging devices, and insulating windows are examples of:',
          a: ['Energy efficiency', 'Sustainable mobility', 'The linear economy', 'Zero waste'], correct: 0 },
        { q: 'Which action best represents the "reuse" step in a circular economy?',
          a: ['Throwing a plastic bottle in the trash', 'Melting down a glass bottle to make a new one',
              'Using a washable cloth bag for groceries instead of taking a new plastic bag every time',
              'Buying a new phone every six months'], correct: 2 },
        { q: 'How does sustainable agriculture protect biodiversity?',
          a: ['By using heavy pesticides to kill all insects',
              'By relying on natural pest control methods and protecting local seed varieties',
              'By cutting down nearby forests to expand farmland', 'By planting only one type of crop across thousands of acres'], correct: 1 },
        { q: 'When making green purchases, what should you actively avoid?',
          a: ['Products made from recycled materials', 'Durable, long-lasting goods',
              'Single-use plastics and disposable items', 'Second-hand clothing'], correct: 2 },
        { q: 'Why is choosing public transport, walking, or cycling considered sustainable mobility?',
          a: ['Because they completely rely on fossil fuels',
              'Because they significantly reduce the carbon footprint and air pollution per person compared to individual petrol cars',
              'Because they are the most expensive ways to travel', 'Because they require building more highways'], correct: 1 },
        { q: 'Why are small, everyday green choices important?',
          a: ['Because small actions, when multiplied by thousands of people, create a powerful movement for systemic change',
              'Because they instantly fix all climate problems overnight',
              'Because individuals are the only ones responsible for climate change',
              'Because green choices are required by international law'], correct: 0 }
      ]}
    ]
  },

  /* ── Module 4 ───────────────────────────────────────────────────── */
  {
    id: 'm4', n: 4,
    title: 'From Learner to Leader — Green Careers, Activism & Impact',
    summary: 'Turning what you know into work, advocacy and enterprise.',
    units: [
      { id: 'm4-i', kind: 'video', title: 'Introduction', yt: 'RrLpwJZKIpY' },
      { id: 'm4-1', kind: 'video', title: '4.1 Green Jobs', yt: '1oo6JJ5vglE',
        quiz: { title: 'Check what you learned', q: [
          { q: 'How does the video define green jobs?',
            a: ['Jobs that only exist in national parks and forests',
                'Professions that contribute to environmental protection, climate change mitigation, and sustainable development',
                'Jobs that focus exclusively on increasing corporate profits without considering nature',
                'Any job that involves working outdoors'], correct: 1,
            why: 'A green job is defined by its contribution, not its location.' },
          { q: 'What types of skills are required in the green job market?',
            a: ['Only technical skills like engineering and data analysis',
                'Only soft skills like public speaking and teamwork',
                'A combination of technical skills (e.g. energy system design) and soft skills (e.g. communication and project management)',
                'Green jobs do not require any specialized skills'], correct: 2,
            why: 'The work is interdisciplinary, so the skill set has to be too.' }
        ]}},
      { id: 'm4-2', kind: 'video', title: '4.2 Green Careers', yt: '6FqrUmei9f4',
        quiz: { title: 'Check what you learned', q: [
          { q: 'What is recommended for applying theoretical knowledge in real conditions?',
            a: ['Watching movies about nature', 'Applying for high-level management positions immediately',
                'Doing volunteer work and completing internships', 'Only reading textbooks without doing field work'], correct: 2,
            why: 'Volunteering and internships build both experience and the network that carries a career.' },
          { q: 'Which of the following is true about starting a green career?',
            a: ["You can only have a green career with a Master's degree in science",
                'You must work for a large international organization',
                'It can involve starting your own eco-startup, such as a recycling service or educational programme',
                'You cannot transition into a green career from a different field'], correct: 2,
            why: 'Entrepreneurship is a legitimate entry route, and career switching is common.' }
        ]}},
      { id: 'm4-3', kind: 'video', title: '4.3 Activism & Advocacy', yt: '1cptnONhCKQ',
        quiz: { title: 'Check what you learned', q: [
          { q: 'What is the main difference between activism and advocacy?',
            a: ['Activism is only for politicians, while advocacy is for students',
                'Activism focuses on actions like peaceful protests and social media campaigns, while advocacy works to change policies and laws by presenting arguments to decision-makers',
                'Activism requires a lot of money, while advocacy is always free',
                'There is no difference; both words mean the same thing'], correct: 1,
            why: 'Activism mobilises public attention; advocacy works the levers of policy.' },
          { q: 'Which is a key to successful activism and advocacy?',
            a: ['Acting alone without building partnerships', 'Making demands without researching the issue first',
                'Using highly academic language that the general public cannot understand',
                'Researching the issue, relying on clear facts, and setting measurable, achievable goals'], correct: 3,
            why: 'Evidence and achievable goals are what turn noise into change.' }
        ]}},
      { id: 'm4-4', kind: 'video', title: '4.4 Entrepreneurship', yt: '9xW3inhTUXQ',
        quiz: { title: 'Check what you learned', q: [
          { q: 'What is the primary definition of social entrepreneurship?',
            a: ['A business model aimed at solving social or environmental problems while ensuring financial stability',
                'A charity that relies entirely on donations to survive',
                'A business that maximizes financial profit by ignoring environmental regulations',
                'A government programme that funds local parks'], correct: 0,
            why: 'It pairs a social or environmental mission with a viable business model.' },
          { q: 'What is the first step recommended for starting a community initiative?',
            a: ['Creating a detailed financial plan', 'Identifying the specific problem or issue that you care about the most',
                'Finding investors to give you money', 'Building a website'], correct: 1,
            why: 'Start from the problem you genuinely care about; everything else follows from it.' }
        ]}},
      { id: 'm4-s', kind: 'video', title: 'Module summary', yt: 'l5P_aNNf1DI' },
      { id: 'm4-f', kind: 'quiz', title: 'Module 4 final quiz', q: [
        { q: 'Which profession is an example of a green job?',
          a: ['An engineer designing solar power stations', 'A manager at a coal mining facility',
              'A salesperson for single-use plastics', 'A fast-fashion clothing designer'], correct: 0 },
        { q: 'Why are soft skills important for green careers?',
          a: ['Because technical skills are completely useless in environmental science',
              'Because solving climate issues requires collaborating with others, managing projects, and conveying ideas effectively',
              'Because green jobs do not involve any real data or science', 'Soft skills are not actually important'], correct: 1 },
        { q: 'If you want a green career but lack experience, what is the best first step?',
          a: ['Wait until someone offers you a high-paying job',
              'Volunteer or do an internship to gain practical experience and network',
              'Abandon your current studies', 'Start a massive international company immediately'], correct: 1 },
        { q: 'Organizing a peaceful march and social media campaign about a polluted river is an example of:',
          a: ['Eco-entrepreneurship', 'Advocacy', 'Activism', 'Circular economy'], correct: 2 },
        { q: 'Preparing a research-based proposal and meeting officials to ban plastic bags is an example of:',
          a: ['Activism', 'Advocacy', 'Social media marketing', 'Volunteering'], correct: 1 },
        { q: 'What makes an advocacy campaign effective?',
          a: ['Choosing the right audience and communicating in a language they understand',
              'Making sure the goals are impossible to achieve to show ambition',
              'Refusing to work with other groups or communities', 'Relying purely on emotions rather than facts'], correct: 0 },
        { q: 'How does an eco-enterprise differ from a traditional business?',
          a: ['It makes money by extracting fossil fuels',
              'Its core focus is solving environmental problems while remaining financially sustainable',
              'It is strictly a non-profit that cannot make any money', 'It does not require a team or a business plan'], correct: 1 },
        { q: 'Why are small community initiatives important?',
          a: ['They instantly solve global climate change on their own', 'They replace the need for national laws',
              'They connect people, build community solidarity, and raise a sense of shared responsibility',
              'They generate massive financial profits for the organizers'], correct: 2 },
        { q: 'After identifying the problem, what should you do next?',
          a: ['Give up if it seems too hard', 'Build a team and find like-minded people to join forces with',
              'Ask the government to solve it for you', 'Write a book about it'], correct: 1 },
        { q: 'What is the ultimate message of Module 4 regarding leadership?',
          a: ['You must be an elected official or have a fancy job title to be a leader',
              'Leadership means telling other people what to do while you relax',
              'Anyone with an idea who is willing to take responsibility and engage others can become a driving force for change',
              'Only older generations have the experience to be true environmental leaders'], correct: 2 }
      ]}
    ]
  }
  ],

  outro: { id: 'outro', kind: 'video', title: 'We end the course, but not the fight', yt: '12ZQsW1Gp-A' },

  /* ── Final exam ─────────────────────────────────────────────────── */
  exam: {
    id: 'final', kind: 'quiz', title: 'Comprehensive final exam',
    blurb: 'Twenty questions across all four modules. Score 80% or higher to claim your certificate.',
    q: [
      { q: 'What does systems thinking teach us about the environment, society, and economy?',
        a: ['That they operate completely independently of one another',
            'That everything is interconnected, and a single change in one area causes ripple effects in the others',
            'That economic growth is the only factor that matters for long-term survival',
            'That human activities cannot influence large natural ecosystems'], correct: 1 },
      { q: 'Melting glaciers exposing darker surfaces that absorb more heat is an example of:',
        a: ['A negative feedback loop', 'The circular economy', 'A positive feedback loop', 'Environmental justice'], correct: 2 },
      { q: 'What happens if the three pillars of sustainability are out of balance?',
        a: ['The entire structure of sustainable development collapses', 'The economy grows at a much faster rate',
            'Society automatically adapts to the changes', 'The environment recovers on its own'], correct: 0 },
      { q: 'What is the core principle of environmental justice?',
        a: ['Wealthy countries should have exclusive access to clean water',
            'Environmental laws should only apply to industrial factories',
            'Every person, regardless of location, social status, or abilities, has an equal right to a clean, safe environment',
            'Only rural areas need environmental protection'], correct: 2 },
      { q: 'How do the SDGs demonstrate systems thinking on a global scale?',
        a: ['They prove that environmental goals are completely separate from economic goals',
            'Achieving one goal (like SDG 15: Life on Land) actively supports other goals (like SDG 13: Climate Action)',
            'They require countries to complete them one by one in a strict order',
            'They only apply to international organizations, not local communities'], correct: 1 },
      { q: 'What is the main difference between climate and weather?',
        a: ['Climate refers to the oceans, while weather refers to the atmosphere',
            'Climate is the long-term, stable average of conditions, while weather is the short-term, daily change',
            'Climate and weather mean the exact same thing', 'Weather is caused by humans, while climate is purely natural'], correct: 1 },
      { q: 'Which best describes the natural greenhouse effect?',
        a: ['A process where gases like CO2 trap heat to keep the Earth warm enough for life, currently being dangerously amplified by human emissions',
            'A man-made invention created during the Industrial Revolution to grow crops',
            'The process of the ozone layer reflecting sunlight back into space',
            'The temporary cooling of the Earth caused by volcanic ash'], correct: 0 },
      { q: 'How do scientists know current warming is driven by humans and not Milankovitch cycles?',
        a: ["Because the sun's temperature has doubled in the last century",
            'Because according to natural orbital cycles the Earth should currently be cooling, yet it is rapidly warming',
            'Because volcanoes have stopped erupting completely', 'Because Milankovitch cycles only happen on other planets'], correct: 1 },
      { q: 'Which is a specific climate change impact currently threatening Armenia?',
        a: ['Expanding glaciers in the southern regions',
            'Severe drops in groundwater levels in the Ararat Valley and frequent algal blooms in Lake Sevan',
            'Massive increases in annual rainfall causing year-round flooding', 'The complete freezing of all national rivers'], correct: 1 },
      { q: 'Transitioning to solar energy is an example of ___, while drought-resistant irrigation is an example of ___.',
        a: ['Adaptation; mitigation', 'Mitigation; adaptation', 'Circular economy; linear economy', 'Advocacy; activism'], correct: 1 },
      { q: 'In a circular economy, what is the ultimate goal?',
        a: ['To produce goods as cheaply as possible, use them once, and throw them away',
            'To keep resources in use for as long as possible through recycling, repairing, and reusing, eliminating waste',
            'To only use plastic packaging for all products', 'To stop all global manufacturing permanently'], correct: 1 },
      { q: 'Why is a short supply chain better for the climate?',
        a: ['It requires heavy use of chemical preservatives',
            'It requires less transportation, storage, and processing, significantly reducing greenhouse gas emissions',
            'It relies heavily on international airplanes and cargo ships', 'Local food always requires more plastic packaging'], correct: 1 },
      { q: 'Which is a key practice of sustainable agriculture?',
        a: ['Using massive amounts of chemical fertilizers to speed up crop growth',
            'Destroying local biodiversity to plant a single, highly profitable crop',
            'Using water efficiently (like drip irrigation) and promoting natural pest control',
            'Cutting down forests to create more grazing land for cattle'], correct: 2 },
      { q: 'Using LED bulbs, insulating buildings, and energy-saving appliances are examples of:',
        a: ['Sustainable mobility', 'Energy efficiency', 'Renewable energy generation', 'Zero waste'], correct: 1 },
      { q: 'What does supporting slow fashion mean in everyday life?',
        a: ['Buying cheap, trendy clothes every week and throwing them away when they tear',
            'Wearing clothes that take a long time to manufacture using fossil fuels',
            'Choosing high-quality, long-lasting clothing, buying second-hand, and avoiding disposable fashion trends',
            'Only wearing clothes made from single-use plastics'], correct: 2 },
      { q: 'Which best defines a green job?',
        a: ['Any job that takes place outside of an office building',
            'A profession that actively contributes to environmental protection, climate change mitigation, and sustainable development',
            'A job in the fossil fuel industry that pays a high salary', 'A volunteer position that does not require any skills'], correct: 1 },
      { q: 'Why are soft skills highly valued in green careers?',
        a: ['Because technical skills like engineering are completely unnecessary',
            'Because solving complex environmental issues requires collaborating with diverse groups and effectively communicating solutions',
            'Because green jobs only involve public speaking and no actual science',
            'Soft skills are not valued in green careers; only math and data analysis matter'], correct: 1 },
      { q: 'Organizing a community march is an example of ___, while drafting a policy proposal is an example of ___.',
        a: ['Advocacy; activism', 'Activism; advocacy', 'Mitigation; adaptation', 'Entrepreneurship; volunteering'], correct: 1 },
      { q: 'What is the primary purpose of a social eco-enterprise?',
        a: ['To maximize financial profit by ignoring environmental regulations',
            'To operate strictly as a charity with no revenue or business model',
            'To solve a social or environmental problem while maintaining a financially sustainable business model',
            'To sell single-use plastics to local communities'], correct: 2 },
      { q: 'What is the very first step when starting a community initiative?',
        a: ['Ask the government for a massive financial grant',
            'Identify a specific problem that you care deeply about and want to solve',
            'Rent an expensive office space', 'Assume you are the only one who cares and work completely alone'], correct: 1 }
    ]
  }
};
